# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "Ytang520"
repo_name: "LLM-safety-arxiv-daily"
show_authors: True
show_links: True
show_badge: False
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/safety-arxiv-daily.json'
json_gitpage_path: './docs/safety-arxiv-daily-web.json'
json_wechat_path: './docs/safety-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "AI safety":
        filters: ["jailbreaking", "jailbreak", "defense", "red team", "red teaming", "LLM safety", "AI safety"]


